apiVersion: v1
kind: ReplicationController 
metadata:
    name: vertex-rc
spec: 
    replicas: 3
    selector:
        app: mynginx
        version: 2.6.2
    template:
      metadata:
        labels:
          app: mynginx
          version: 2.6.2
      spec:
          containers:
          - name: mynginx-container
            image: nginx
            ports:
            - containerPort: 80